name: uttil
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:

  # State management
  provider: ^6.1.2
  flutter_bloc: ^8.1.4

  # Code generation
  equatable: ^2.0.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9

  # DI
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0

  # Router
  go_router: ^13.2.0

  # Utils
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  bot_toast: ^4.0.1

  flutter:
    sdk: flutter


# TODO: Check this dependecies in order to remove the unnecesary ones
  get: ^4.6.5
  http: 
  get_storage: ^2.1.1
  fluttertoast: ^8.2.2
  shared_preferences: ^2.0.17
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0
  table_calendar:
  google_maps_flutter: ^2.2.3
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_google_places_hoc081098: ^1.2.0 
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers:
  syncfusion_flutter_sliders: ^25.1.39
  syncfusion_flutter_charts: ^25.1.39+1
  timeline_tile: ^2.0.0
  imageview360: ^1.3.0
# ------

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  build_runner: ^2.4.8
  floor_generator: ^1.4.2
  flutter_lints: ^3.0.1
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  retrofit_generator: ^8.1.0

  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - config/

  fonts:
    - family: Gilroy Black
      fonts:
        - asset: assets/fonts/Gilroy-Black.otf
    - family: Gilroy Light
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
    - family: Gilroy Heavy
      fonts:
        - asset: assets/fonts/Gilroy-Heavy.otf
    - family: Gilroy Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.otf
    - family: Gilroy Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.otf
    - family: Gilroy ExtraBold
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
    - family: Gilroy Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.otf